trigger:
- az-pipeline

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: validate
  displayName: 'Terraform validate'
  jobs:
  - job: TerraformValidate
    displayName: 'Terraform validate'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          export TF_VAR_api_key="$(api_key)"
          terraform init
          terraform validate 
      displayName: 'Terraform validate'

- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          export TF_VAR_api_key="$(api_key)"
          terraform --version
          terraform init 
          terraform plan 
      displayName: 'Terraform Init and Plan'
      
- stage: Deploy
  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          export TF_VAR_api_key="$(api_key)"
          terraform init
          terraform apply -input=false -auto-approve
      displayName: 'Terraform Init and Apply'
