trigger:
- az-pipeline

variables:
- group: Newrelic-infra-policy

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Terraform_Plan'
  displayName: 'Terraform Plan'
  jobs:
  - job: 'Terraform_Plan'
    steps:
    - script: |
        echo "Running Terraform init..."
        terraform init
        echo "Running Terraform plan..."
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'
          
        
- stage: 'Terraform_Apply'
  displayName: 'Terraform Apply'
  jobs:
  - job: 'Terraform_Apply'
    steps:
    - script: |
        echo "Running Terraform apply..."
        terraform apply
      displayName: 'Terraform Apply'
             
              








