trigger:
- az-pipeline

variables:
- group: Newrelic-infra-policy

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: 'Replacing_Variables_From_ADO_Secrets_to_Terraform_variables'
  displayName: 'Replacing Variables'
  jobs:
  - job: 'Replacing_Variables_From_ADO_Secrets_to_Terraform_variables'
    steps:
      - task: replacetokens@5
        inputs:
          targetFiles: 'terraform/terraform.tfvars'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true

- stage: 'Terraform_Plan'
  displayName: 'Terraform Plan'
  jobs:
  - job: 'Terraform_Plan'
    steps:
    - script: |
        echo "Running Terraform init..."
        terraform init
        echo "Running Terraform plan..."
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'
          
        
- stage: 'Terraform_Apply'
  displayName: 'Terraform Apply'
  jobs:
  - job: 'Terraform_Apply'
    steps:
    - script: |
        echo "Running Terraform apply..."
        terraform apply -var-file="terraform.tfvars"
      displayName: 'Terraform Apply'
             
              








