parameters:
- name: releaseName
  type: string
  displayName: 'Release Name'
  default: Demo 
- name: major
  type: number
  displayName: 'Major version'
  default: 1 
- name: minor
  type: number
  displayName: 'Minor version'
  default: 0 

trigger:
- az-pipeline

variables:
- group: Newrelic-infra-policy

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'BuildBranchName'
    displayName: 'Build Branch Name'
    jobs:
      - job: 'BranchName'
        variables:
          buildName: ${{parameters.releaseName}}
          majorVersion: ${{parameters.major}}
          minorVersion: ${{parameters.minor}}
          branchPRNumber: $[counter(variables['System.PullRequest.PullRequestId'], 0)]
          branchBuildNumber: $[counter(variables['Build.SourceBranch'], 0)]
        displayName: 'BranchName'
        steps:
        - template: 'cicd/templates/buildBranchName.yml'



